# Gitpod 配置
# .gitpod.yml文件告诉 Gitpod：
# 在启动工作区时先安装依赖（yarn install）
# 然后启动你的应用（yarn run start）
# 监听应用的 5042 端口，并在启动后自动在浏览器中打开该端口（但仅自己可见）
# tasks: 定义在 Gitpod 工作空间启动时要执行的任务（可以有多个任务）
tasks:
  - init: yarn install
    command: yarn run start
ports:
  - port: 5042
    visibility: private
    onOpen: open-browser