// =====================================================================
// experimental-apis.d.ts —— 实验性 / 浏览器新 API 的全局类型声明（集中）
// 这些 API 在标准 TypeScript DOM lib 中缺失或仅作为类型（非常量）存在，
// 此处统一声明为 any，避免各 api-lab 页面文件各自 declare global 造成重声明冲突。
// 注意：若某 API 在 lib 中已作为 const 值声明，此处再声明会触发 TS2451，
//      需运行 tsc 检测后将该 API 从本文件移除。
// =====================================================================

declare global {
  // 实验性 API 常量（用于 typeof / new / 静态方法调用）
  const AC: any;
  const AI: any;
  const AISession: any;
  const AbsoluteOrientationSensor: any;
  const Accelerometer: any;
  const AggregateError: any;
  const AmbientLightSensor: any;
  const Animation: any;
  const AnimationTimeline: any;
  const AsyncContext: any;
  const AsyncDisposableStack: any;
  const AsyncIterator: any;
  const AsyncLocalStorage: any;
  const AsyncRange: any;
  const Atomics: any;
  const AttrPart: any;
  const Audio: any;
  const AudioData: any;
  const AudioDecoder: any;
  const AudioEncoder: any;
  const AudioWorkletGlobalScope: any;
  const AudioWorkletProcessor: any;
  const BC: any;
  const BackgroundFetchManager: any;
  const BarcodeDetector: any;
  const BarcodeDetectorOptions: any;
  const BarcodeFormat: any;
  const Bluetooth: any;
  const BluetoothDevice: any;
  const BooleanPart: any;
  const BreakToken: any;
  const Button: any;
  const CCIDOverWebUSB: any;
  const CSSCustomHighlightEvent: any;
  const CSSMathMax: any;
  const CSSMathNegate: any;
  const CSSNumberValue: any;
  const Calculator: any;
  const CaptureController: any;
  const Card: any;
  const CharacterBoundsUpdateEvent: any;
  const ChildNodePart: any;
  const ClipboardEvent: any;
  const ClipboardItem: any;
  const ContactAddress: any;
  const ContactPicker: any;
  const ContactsManager: any;
  const ContentIndex: any;
  const ContentIndexEvent: any;
  const CookieChangeEvent: any;
  const CookieStore: any;
  const CookieStoreManager: any;
  const Ctor: any;
  const DOMException: any;
  const DataTransfer: any;
  const DataTransferItem: any;
  const DataTransferItemList: any;
  const DebugInfo: any;
  const DedicatedWorkerGlobalScope: any;
  const DelegatedInkTrailPresenter: any;
  const DigitalCredential: any;
  const DisposableStack: any;
  const DocumentPartRoot: any;
  const DocumentPictureInPicture: any;
  const DocumentPictureInPictureEvent: any;
  const DocumentTimeline: any;
  const DragEvent: any;
  const EditContext: any;
  const ElementInternals: any;
  const ElementPartRoot: any;
  const EncodedAudioChunk: any;
  const EncodedVideoChunk: any;
  const EncryptedMediaKey: any;
  const EventPart: any;
  const EyeDropper: any;
  const EyeDropperOpenResult: any;
  const FaceDetector: any;
  const FederatedCredential: any;
  const FetchLaterResult: any;
  const FileReaderSync: any;
  const FileSystemAccessHandle: any;
  const FileSystemDirectoryHandle: any;
  const FileSystemFileHandle: any;
  const FileSystemWritableFileStream: any;
  const FinalizationRegistry: any;
  const Float16Array: any;
  const FontFace: any;
  const FormDataEvent: any;
  const GPU: any;
  const GPUAdapter: any;
  const GPUBindGroup: any;
  const GPUBindGroupLayout: any;
  const GPUBuffer: any;
  const GPUCommandBuffer: any;
  const GPUCommandEncoder: any;
  const GPUComputePassEncoder: any;
  const GPUComputePipeline: any;
  const GPUDevice: any;
  const GPUExternalTexture: any;
  const GPUPipelineLayout: any;
  const GPUQuerySet: any;
  const GPUQueue: any;
  const GPURenderBundle: any;
  const GPURenderBundleEncoder: any;
  const GPURenderPassEncoder: any;
  const GPURenderPipeline: any;
  const GPUSampler: any;
  const GPUShaderModule: any;
  const GPUTexture: any;
  const GPUTextureView: any;
  const Gadget: any;
  const GamepadHapticActuator: any;
  const GravitySensor: any;
  const Gyroscope: any;
  const HTMLUnknownElement: any;
  const Highlight: any;
  const HighlightRegistry: any;
  const Hls: any;
  const IO: any;
  const IdentityCredential: any;
  const IdentityProvider: any;
  const IdleDetector: any;
  const Image: any;
  const ImageCapture: any;
  const ImageDecoder: any;
  const ImageTrack: any;
  const ImageTrackList: any;
  const InferenceSession: any;
  const Ink: any;
  const Input: any;
  const InputDeviceCapabilities: any;
  const InputEvent: any;
  const Iterator: any;
  const Keyboard: any;
  const KeyboardLayoutMap: any;
  const KeyframeEffect: any;
  const LanguageDetector: any;
  const LanguageModel: any;
  const LinearAccelerationSensor: any;
  const LocalMediaStream: any;
  const Lock: any;
  const MIDIAccess: any;
  const MIDIConnectionEvent: any;
  const MIDIInput: any;
  const MIDIMessageEvent: any;
  const MIDIOutput: any;
  const MIDIPort: any;
  const MLCompiledModel: any;
  const MLContext: any;
  const MLGraph: any;
  const MLGraphBuilder: any;
  const MLOperand: any;
  const MLTensor: any;
  const Magnetometer: any;
  const ManagedMediaSource: any;
  const ManagedSourceBuffer: any;
  const MediaImage: any;
  const MediaKeySession: any;
  const MediaKeySystemAccess: any;
  const MediaMetadata: any;
  const MediaPositionState: any;
  const MediaSessionAction: any;
  const MediaSessionActionDetails: any;
  const MediaSource: any;
  const MediaStreamTrackGenerator: any;
  const MediaStreamTrackProcessor: any;
  const MyArray: any;
  const NDEFMessage: any;
  const NDEFReader: any;
  const NFC: any;
  const NavigateEvent: any;
  const Navigation: any;
  const NavigationCurrentChange: any;
  const NavigationDestination: any;
  const NavigationTransition: any;
  const NavigatorUAData: any;
  const NavigatorUADataBrand: any;
  const NavigatorUADataPlatform: any;
  const OTPCredential: any;
  const OfflineAudioContext: any;
  const Option: any;
  const Pagination: any;
  const PannerNode: any;
  const Part: any;
  const PartGroup: any;
  const PasswordCredential: any;
  const PaymentRequest: any;
  const PerformanceLongAnimationFrameEntry: any;
  const PeriodicSyncManager: any;
  const PointerEvent: any;
  const PressureObserver: any;
  const PressureRecord: any;
  const Prompt: any;
  const PropertyPart: any;
  const PublicKeyCredential: any;
  const RTCEncodedAudioFrame: any;
  const RTCEncodedTransform: any;
  const RTCEncodedVideoFrame: any;
  const RTCRtpScriptTransformer: any;
  const RTCRtpTransform: any;
  const RTCStatsReport: any;
  const RTCTransformEvent: any;
  const RelativeOrientationSensor: any;
  const RemoteSigner: any;
  const ResonanceAudio: any;
  const RestrictionTarget: any;
  const Rewriter: any;
  const SR: any;
  const SSEAdapter: any;
  const SVGElement: any;
  const SVGPathElement: any;
  const SVGTransform: any;
  const Sanitizer: any;
  const Scheduler: any;
  const Scheduling: any;
  const ScrollTimeline: any;
  const SecurityPolicyViolationEvent: any;
  const Sensor: any;
  const SensorErrorEvent: any;
  const Serial: any;
  const SerialPort: any;
  const ShadowRealm: any;
  const SharedArray: any;
  const SharedMap: any;
  const SharedStruct: any;
  const SharedWorkerGlobalScope: any;
  const ShowVirtualKeyboardEvent: any;
  const Snapshot: any;
  const SourceBuffer: any;
  const SourceBufferList: any;
  const SpatialAudioListener: any;
  const SpeechGrammarList: any;
  const SpeechRecognition: any;
  const SpeechSynthesisUtterance: any;
  const SpeechSynthesisVoice: any;
  const StorageBucket: any;
  const StorageBucketManager: any;
  const Summarizer: any;
  const SuppressedError: any;
  const SyncManager: any;
  const TaskController: any;
  const TaskPriorityChangeEvent: any;
  const TaskSignal: any;
  const TemplateInstance: any;
  const TextDetector: any;
  const TextFormat: any;
  const TextFormatUpdateEvent: any;
  const TextUpdateEvent: any;
  const TouchEvent: any;
  const TracedGadget: any;
  const Translation: any;
  const Translator: any;
  const TranslatorLanguage: any;
  const TrustedHTML: any;
  const TrustedScript: any;
  const TrustedScriptURL: any;
  const TrustedTypePolicy: any;
  const TrustedTypePolicyFactory: any;
  const USB: any;
  const USBDevice: any;
  const ValidityState: any;
  const VideoDecoder: any;
  const VideoEncoder: any;
  const VideoFrame: any;
  const ViewTimeline: any;
  const ViewTransition: any;
  const VirtualKeyboard: any;
  const VirtualKeyboardOverlayPolicy: any;
  const WSAdapter: any;
  const WSS: any;
  const WSSAdapter: any;
  const WakeLock: any;
  const WakeLockSentinel: any;
  const WeakRef: any;
  const WebSocketStream: any;
  const WebSocketStreamError: any;
  const WebTransport: any;
  const WebTransportAdapter: any;
  const WebTransportBidirectionalStream: any;
  const WebTransportDatagramDuplexStream: any;
  const WebTransportError: any;
  const WebTransportReceiveStream: any;
  const WebTransportSendStream: any;
  const WorkletAnimation: any;
  const Writer: any;
  const XRAnchor: any;
  const XRAnchorSet: any;
  const XRBoundedReferenceSpace: any;
  const XRCPUDepthInformation: any;
  const XRCamera: any;
  const XRCubeLayer: any;
  const XRCylinderLayer: any;
  const XRDOMOverlayState: any;
  const XREquirectLayer: any;
  const XRFrame: any;
  const XRHitTestResult: any;
  const XRHitTestSource: any;
  const XRInputSource: any;
  const XRInputSourceArray: any;
  const XRLayer: any;
  const XRLightProbe: any;
  const XRPlane: any;
  const XRProjectionLayer: any;
  const XRQuadLayer: any;
  const XRReferenceSpace: any;
  const XRRenderState: any;
  const XRRigidTransform: any;
  const XRSession: any;
  const XRSpace: any;
  const XRSystem: any;
  const XRTransientInputHitTestSource: any;
  const XRView: any;
  const XRViewport: any;
  const XRWebGLBinding: any;
  const XRWebGLDepthInformation: any;
  const XRWebGLLayer: any;
  const XXX: any;

  interface Window {
    bluetooth?: any;
    delegatedInkTrail?: any;
    deviceMemory?: any;
    documentPictureInPicture?: any;
    globalPrivacyControl?: any;
    hid?: any;
    ink?: any;
    managed?: any;
    orientation?: any;
    presentation?: any;
    scheduling?: any;
    screen?: any;
    serial?: any;
    taintEnabled?: any;
    translation?: any;
    usb?: any;
    userAgentData?: any;
    virtualKeyboard?: any;
    visualViewport?: any;
    xr?: any;
    launchQueue?: any;
    digitalGoods?: any;
    LanguageDetector?: any;
    Translator?: any;
    Summarizer?: any;
    LanguageModel?: any;
    Writer?: any;
    Rewriter?: any;
    MLGraphBuilder?: any;
    MLContext?: any;
    MLGraph?: any;
    MLCompiledModel?: any;
    WebTransportSendStream?: any;
    WebTransportReceiveStream?: any;
    NDEFReader?: any;
    OTPCredential?: any;
    PressureObserver?: any;
    digitalGoodsService?: any;
    scheduler?: any;
    BarcodeDetector?: any;
    CaptureController?: any;
    EyeDropper?: any;
    FaceDetector?: any;
    TextDetector?: any;
    IdleDetector?: any;
    USB?: any;
    Serial?: any;
    HID?: any;
    SmartCardContext?: any;
    smartCard?: any;
    PCSCInterface?: any;
    SmartCardConnection?: any;
    policy?: any;
    featurePolicy?: any;
    isSecureContext?: boolean;
  }

  interface Navigator {
    ai?: any;
    bluetooth?: any;
    delegatedInkTrail?: any;
    deviceMemory?: any;
    globalPrivacyControl?: any;
    gpu?: any;
    hid?: any;
    ink?: any;
    managed?: any;
    ml?: any;
    presentation?: any;
    scheduling?: any;
    serial?: any;
    taintEnabled?: any;
    translation?: any;
    usb?: any;
    userAgentData?: any;
    virtualKeyboard?: any;
    xr?: any;
    digitalGoodsService?: any;
    runAdAuction?(config?: any): Promise<any>;
    joinAdInterestGroup?(config?: any): Promise<void>;
    leaveAdInterestGroup?(config?: any): Promise<void>;
    requestMIDIAccess?(options?: any): Promise<any>;
    getGamepads?(): any[];
    setSinkId?(sinkId: string): Promise<void>;
    smartCard?: any;
  }
}

export {};
