import type { YtDlpConfig } from './types'

// 默认配置：常用且安全的初始值
export const DEFAULT_CONFIG: YtDlpConfig = {
  urls: '',
  outputDir: '',
  outputTemplate: '%(title)s.%(ext)s',
  restrictFilenames: false,
  noOverwrites: false,
  forceOverwrites: false,
  continue: true,
  noPart: false,
  writeThumbnail: false,
  writeInfoJson: false,

  formatMode: 'quick',
  quickFormat: 'best',
  customFormat: '',
  formatSort: '',
  preferFree: false,
  container: 'auto',

  extractAudio: false,
  audioFormat: 'best',
  audioQuality: '0',

  proxy: '',
  socketTimeout: '',
  rateLimit: '',
  minFilesize: '',
  maxFilesize: '',
  retries: '10',
  fragmentRetries: '10',
  concurrentFragments: '1',
  bufferSize: '',

  geoBypass: false,
  geoBypassCountry: '',
  forceIpv4: false,
  forceIpv6: false,

  writeSubs: false,
  writeAutoSubs: false,
  subLangs: 'en',
  subFormat: 'best',
  embedSubs: false,
  embedMetadata: false,
  embedThumbnail: false,
  addMetadata: false,

  recodeVideo: '',
  remuxVideo: '',
  splitChapters: false,
  removeChapters: '',
  externalDownloader: 'none',
  externalDownloaderArgs: '',
  ffmpegLocation: '',
  postprocessorArgs: '',

  cookiesFromBrowser: 'none',
  cookiesFile: '',
  username: '',
  password: '',
  videoPassword: '',

  playlistItems: '',
  playlistStart: '',
  playlistEnd: '',
  playlistReverse: false,
  playlistRandom: false,
  noPlaylist: false,

  simulate: false,
  quiet: false,
  verbose: false,
  ignoreErrors: false,
  noWarnings: false,
  skipDownload: false,
  print: '',
  dumpJson: false,
  listFormats: false,
  listSubs: false,
  noCheckCertificate: false,
  encoding: '',

  downloadArchive: '',
  ageLimit: '',
  matchFilter: '',
  matchTitle: '',
  rejectTitle: '',
  date: '',
  datebefore: '',
  dateafter: '',
  minViews: '',
  maxViews: '',

  parseMetadata: '',
  metadataFromTitle: '',
  xattrs: false,
  exec: '',
  execBeforeDownload: '',

  sourceAddress: '',
  sleepInterval: '',
  maxSleepInterval: '',

  cacheDir: '',
  noCacheDir: false,
  trimFileName: '',

  apMso: '',
  apUsername: '',
  apPassword: '',
}