import type { OptionDef } from './types'

// yt-dlp 全量选项目录：作为选项配置中心表单与帮助文档的唯一数据源
export const OPTIONS_CATALOG: OptionDef[] = [
  // ============ 通用选项 ============
  {
    id: 'outputDir',
    flag: '--paths',
    shortFlag: '-P',
    label: '输出目录',
    desc: '指定下载文件的保存路径，如 ~/Downloads',
    category: 'general',
    type: 'text',
    placeholder: '~/Downloads',
    argName: 'PATH',
  },
  {
    id: 'outputTemplate',
    flag: '--output',
    shortFlag: '-o',
    label: '输出文件名模板',
    desc: '命名模板，支持变量如 %(title)s.%(ext)s、%(upload_date)s 等',
    category: 'general',
    type: 'text',
    placeholder: '%(title)s.%(ext)s',
    argName: 'TEMPLATE',
  },
  {
    id: 'restrictFilenames',
    flag: '--restrict-filenames',
    label: '限制文件名字符',
    desc: '仅使用 ASCII 字符与下划线，避免特殊字符问题',
    category: 'general',
    type: 'switch',
  },
  {
    id: 'noOverwrites',
    flag: '--no-overwrites',
    label: '不覆盖已存在文件',
    desc: '跳过已下载完成的文件',
    category: 'general',
    type: 'switch',
  },
  {
    id: 'forceOverwrites',
    flag: '--force-overwrites',
    label: '强制覆盖',
    desc: '始终覆盖已存在的文件',
    category: 'general',
    type: 'switch',
  },
  {
    id: 'continue',
    flag: '--continue',
    shortFlag: '-c',
    label: '断点续传',
    desc: '恢复未完成的下载（默认开启）',
    category: 'general',
    type: 'switch',
  },
  {
    id: 'noPart',
    flag: '--no-part',
    label: '不使用 .part 文件',
    desc: '直接写入最终文件名，不生成临时文件',
    category: 'general',
    type: 'switch',
  },
  {
    id: 'writeThumbnail',
    flag: '--write-thumbnail',
    label: '保存封面图',
    desc: '将视频封面保存为图片文件',
    category: 'general',
    type: 'switch',
  },
  {
    id: 'writeInfoJson',
    flag: '--write-info-json',
    label: '保存元数据 JSON',
    desc: '将视频信息写入 .info.json 文件',
    category: 'general',
    type: 'switch',
  },
  {
    id: 'ignoreErrors',
    flag: '--ignore-errors',
    shortFlag: '-i',
    label: '忽略错误继续',
    desc: '遇到错误时跳过，继续下载后续内容',
    category: 'general',
    type: 'switch',
  },

  // ============ 格式选择 ============
  {
    id: 'customFormat',
    flag: '--format',
    shortFlag: '-f',
    label: '自定义格式表达式',
    desc: '手动指定格式选择表达式，如 bestvideo+bestaudio/best',
    category: 'selection',
    type: 'text',
    placeholder: 'bestvideo+bestaudio/best',
    argName: 'FORMAT',
  },
  {
    id: 'formatSort',
    flag: '--format-sort',
    shortFlag: '-S',
    label: '格式排序偏好',
    desc: '按属性排序选择格式，如 res:1080,vcodec:av1',
    category: 'selection',
    type: 'text',
    placeholder: 'res:1080,vcodec:av1',
    argName: 'SORT',
  },
  {
    id: 'preferFree',
    flag: '--prefer-free-formats',
    label: '优先免费格式',
    desc: '优先选择免版税/开源编码格式',
    category: 'selection',
    type: 'switch',
  },
  {
    id: 'container',
    flag: '--merge-output-format',
    label: '合并输出容器',
    desc: '合并视频与音频时的封装格式',
    category: 'selection',
    type: 'select',
    options: [
      { value: 'auto', label: '自动' },
      { value: 'mp4', label: 'MP4' },
      { value: 'mkv', label: 'MKV' },
      { value: 'webm', label: 'WebM' },
      { value: 'flv', label: 'FLV' },
    ],
  },

  // ============ 音频提取 ============
  {
    id: 'extractAudio',
    flag: '--extract-audio',
    shortFlag: '-x',
    label: '提取纯音频',
    desc: '仅提取音频轨道（自动禁用视频相关选项）',
    category: 'audio',
    type: 'switch',
  },
  {
    id: 'audioFormat',
    flag: '--audio-format',
    label: '音频格式',
    desc: '提取后转换的目标音频格式',
    category: 'audio',
    type: 'select',
    options: [
      { value: 'best', label: '保持原格式' },
      { value: 'mp3', label: 'MP3' },
      { value: 'm4a', label: 'M4A (AAC)' },
      { value: 'flac', label: 'FLAC' },
      { value: 'wav', label: 'WAV' },
      { value: 'opus', label: 'Opus' },
      { value: 'vorbis', label: 'Vorbis' },
    ],
  },
  {
    id: 'audioQuality',
    flag: '--audio-quality',
    label: '音频质量',
    desc: '转换质量，0 为最佳，10 为最差（VBR）',
    category: 'audio',
    type: 'select',
    options: [
      { value: '0', label: '最佳 (0)' },
      { value: '2', label: '高 (2)' },
      { value: '5', label: '中等 (5)' },
      { value: '8', label: '低 (8)' },
      { value: '10', label: '最低 (10)' },
    ],
  },

  // ============ 网络选项 ============
  {
    id: 'proxy',
    flag: '--proxy',
    label: '代理服务器',
    desc: '通过代理访问，支持 http/https/socks4/socks5',
    category: 'network',
    type: 'text',
    placeholder: 'socks5://127.0.0.1:1080',
    argName: 'URL',
  },
  {
    id: 'socketTimeout',
    flag: '--socket-timeout',
    label: '连接超时（秒）',
    desc: '放弃连接前的等待秒数',
    category: 'network',
    type: 'number',
    placeholder: '20',
    argName: 'SECONDS',
  },
  {
    id: 'rateLimit',
    flag: '--limit-rate',
    shortFlag: '-r',
    label: '下载限速',
    desc: '限制最大下载速度，如 500K、2M',
    category: 'network',
    type: 'text',
    placeholder: '2M',
    argName: 'RATE',
  },
  {
    id: 'bufferSize',
    flag: '--buffer-size',
    label: '缓冲区大小',
    desc: '下载缓冲区字节数，如 16K',
    category: 'network',
    type: 'text',
    placeholder: '16K',
    argName: 'SIZE',
  },
  {
    id: 'retries',
    flag: '--retries',
    label: '重试次数',
    desc: '下载失败后的重试次数',
    category: 'network',
    type: 'number',
    placeholder: '10',
    argName: 'RETRIES',
  },
  {
    id: 'fragmentRetries',
    flag: '--fragment-retries',
    label: '分片重试次数',
    desc: '分片下载失败的重试次数',
    category: 'network',
    type: 'number',
    placeholder: '10',
    argName: 'RETRIES',
  },
  {
    id: 'concurrentFragments',
    flag: '--concurrent-fragments',
    shortFlag: '-N',
    label: '并发分片数',
    desc: '同时下载的分片数量',
    category: 'network',
    type: 'number',
    placeholder: '1',
    argName: 'N',
  },
  {
    id: 'minFilesize',
    flag: '--min-filesize',
    label: '最小文件大小',
    desc: '不下载小于此大小的文件',
    category: 'network',
    type: 'text',
    placeholder: '1M',
    argName: 'SIZE',
  },
  {
    id: 'maxFilesize',
    flag: '--max-filesize',
    label: '最大文件大小',
    desc: '不下载大于此大小的文件',
    category: 'network',
    type: 'text',
    placeholder: '500M',
    argName: 'SIZE',
  },
  {
    id: 'sourceAddress',
    flag: '--source-address',
    label: '源 IP 地址',
    desc: '绑定客户端使用的源 IP 地址',
    category: 'network',
    type: 'text',
    placeholder: '0.0.0.0',
    argName: 'IP',
  },
  {
    id: 'sleepInterval',
    flag: '--sleep-interval',
    label: '请求间隔',
    desc: '每次下载前休眠的秒数，用于限流',
    category: 'network',
    type: 'number',
    placeholder: '3',
    argName: 'SECONDS',
  },
  {
    id: 'maxSleepInterval',
    flag: '--max-sleep-interval',
    label: '最大间隔',
    desc: '随机休眠的最大秒数，配合请求间隔使用',
    category: 'network',
    type: 'number',
    placeholder: '10',
    argName: 'SECONDS',
  },

  // ============ 地理限制 ============
  {
    id: 'geoBypass',
    flag: '--geo-bypass',
    label: '绕过地理限制',
    desc: '绕过基于 IP 的地理限制',
    category: 'geo',
    type: 'switch',
  },
  {
    id: 'geoBypassCountry',
    flag: '--geo-bypass-country',
    label: '伪装国家',
    desc: '使用指定国家代码绕过地理限制，如 US',
    category: 'geo',
    type: 'text',
    placeholder: 'US',
    argName: 'CODE',
  },
  {
    id: 'forceIpv4',
    flag: '--force-ipv4',
    shortFlag: '-4',
    label: '强制 IPv4',
    desc: '所有连接使用 IPv4',
    category: 'geo',
    type: 'switch',
  },
  {
    id: 'forceIpv6',
    flag: '--force-ipv6',
    shortFlag: '-6',
    label: '强制 IPv6',
    desc: '所有连接使用 IPv6',
    category: 'geo',
    type: 'switch',
  },

  // ============ 字幕与元数据 ============
  {
    id: 'writeSubs',
    flag: '--write-subs',
    label: '下载字幕',
    desc: '下载手动上传的字幕文件',
    category: 'subtitle',
    type: 'switch',
  },
  {
    id: 'writeAutoSubs',
    flag: '--write-auto-subs',
    label: '下载自动字幕',
    desc: '下载自动生成的字幕',
    category: 'subtitle',
    type: 'switch',
  },
  {
    id: 'subLangs',
    flag: '--sub-langs',
    label: '字幕语言',
    desc: '指定字幕语言，如 en,zh-Hans 或 all',
    category: 'subtitle',
    type: 'text',
    placeholder: 'en,zh-Hans',
    argName: 'LANGS',
  },
  {
    id: 'subFormat',
    flag: '--sub-format',
    label: '字幕格式',
    desc: '字幕文件格式偏好',
    category: 'subtitle',
    type: 'select',
    options: [
      { value: 'best', label: '最佳' },
      { value: 'srt', label: 'SRT' },
      { value: 'vtt', label: 'VTT' },
      { value: 'ass', label: 'ASS' },
      { value: 'json3', label: 'JSON3' },
    ],
  },
  {
    id: 'embedSubs',
    flag: '--embed-subs',
    label: '嵌入字幕',
    desc: '将字幕嵌入到视频容器中',
    category: 'subtitle',
    type: 'switch',
  },
  {
    id: 'embedMetadata',
    flag: '--embed-metadata',
    label: '嵌入元数据',
    desc: '将标题、作者等元数据写入文件',
    category: 'subtitle',
    type: 'switch',
  },
  {
    id: 'embedThumbnail',
    flag: '--embed-thumbnail',
    label: '嵌入封面',
    desc: '将封面图嵌入到音频/视频文件中',
    category: 'subtitle',
    type: 'switch',
  },
  {
    id: 'addMetadata',
    flag: '--add-metadata',
    label: '写入元数据',
    desc: '向文件写入元数据（旧版选项）',
    category: 'subtitle',
    type: 'switch',
  },

  // ============ 后处理 ============
  {
    id: 'recodeVideo',
    flag: '--recode-video',
    label: '重新编码视频',
    desc: '将视频重新编码为指定格式，如 mp4',
    category: 'postprocess',
    type: 'select',
    options: [
      { value: '', label: '不编码' },
      { value: 'mp4', label: 'MP4' },
      { value: 'mkv', label: 'MKV' },
      { value: 'webm', label: 'WebM' },
      { value: 'flv', label: 'FLV' },
    ],
  },
  {
    id: 'remuxVideo',
    flag: '--remux-video',
    label: '无损重封装',
    desc: '无损重封装为指定容器，不重新编码',
    category: 'postprocess',
    type: 'select',
    options: [
      { value: '', label: '不重封装' },
      { value: 'mp4', label: 'MP4' },
      { value: 'mkv', label: 'MKV' },
      { value: 'webm', label: 'WebM' },
    ],
  },
  {
    id: 'splitChapters',
    flag: '--split-chapters',
    label: '按章节拆分',
    desc: '将视频按章节拆分为多个文件',
    category: 'postprocess',
    type: 'switch',
  },
  {
    id: 'removeChapters',
    flag: '--remove-chapters',
    label: '移除章节',
    desc: '移除匹配标题的章节，如 Intro、Outro',
    category: 'postprocess',
    type: 'text',
    placeholder: 'Intro,Outro',
    argName: 'REGEX',
  },
  {
    id: 'externalDownloader',
    flag: '--external-downloader',
    label: '外部下载器',
    desc: '使用外部下载器加速下载',
    category: 'postprocess',
    type: 'select',
    options: [
      { value: 'none', label: '内置下载器' },
      { value: 'aria2c', label: 'aria2c' },
      { value: 'ffmpeg', label: 'ffmpeg' },
      { value: 'avconv', label: 'avconv' },
      { value: 'httpie', label: 'httpie' },
    ],
  },
  {
    id: 'externalDownloaderArgs',
    flag: '--external-downloader-args',
    label: '外部下载器参数',
    desc: '传递给外部下载器的参数',
    category: 'postprocess',
    type: 'text',
    placeholder: '-x 16 -k 1M',
    argName: 'ARGS',
  },
  {
    id: 'ffmpegLocation',
    flag: '--ffmpeg-location',
    label: 'ffmpeg 路径',
    desc: '指定 ffmpeg/ffprobe 可执行文件位置',
    category: 'postprocess',
    type: 'text',
    placeholder: '/usr/local/bin',
    argName: 'PATH',
  },
  {
    id: 'postprocessorArgs',
    flag: '--postprocessor-args',
    label: '后处理参数',
    desc: '传递给 ffmpeg 等后处理器的参数',
    category: 'postprocess',
    type: 'text',
    placeholder: '-c:v libx264 -crf 18',
    argName: 'ARGS',
  },
  {
    id: 'parseMetadata',
    flag: '--parse-metadata',
    label: '解析元数据',
    desc: '从其他字段解析/修改元数据，如 "title:(?P<title>.+)"',
    category: 'postprocess',
    type: 'text',
    placeholder: 'title:(?P<title>.+)',
    argName: 'FIELD',
  },
  {
    id: 'metadataFromTitle',
    flag: '--metadata-from-title',
    label: '标题提取元数据',
    desc: '从视频标题用正则提取元数据字段',
    category: 'postprocess',
    type: 'text',
    placeholder: '%(artist)s - %(title)s',
    argName: 'FORMAT',
  },
  {
    id: 'xattrs',
    flag: '--xattrs',
    label: '写入扩展属性',
    desc: '将元数据写入文件的扩展属性（xattr）',
    category: 'postprocess',
    type: 'switch',
  },
  {
    id: 'exec',
    flag: '--exec',
    label: '下载后执行命令',
    desc: '下载完成后执行的命令，支持 {} 占位符',
    category: 'postprocess',
    type: 'text',
    placeholder: 'echo {}',
    argName: 'CMD',
  },
  {
    id: 'execBeforeDownload',
    flag: '--exec-before-download',
    label: '下载前执行命令',
    desc: '下载开始前执行的命令',
    category: 'postprocess',
    type: 'text',
    placeholder: 'echo starting',
    argName: 'CMD',
  },

  // ============ 身份认证 ============
  {
    id: 'cookiesFromBrowser',
    flag: '--cookies-from-browser',
    label: '浏览器 Cookies',
    desc: '从浏览器读取登录态 Cookies',
    category: 'auth',
    type: 'select',
    options: [
      { value: 'none', label: '不使用' },
      { value: 'chrome', label: 'Chrome' },
      { value: 'firefox', label: 'Firefox' },
      { value: 'edge', label: 'Edge' },
      { value: 'brave', label: 'Brave' },
      { value: 'opera', label: 'Opera' },
      { value: 'safari', label: 'Safari' },
      { value: 'vivaldi', label: 'Vivaldi' },
    ],
  },
  {
    id: 'cookiesFile',
    flag: '--cookies',
    label: 'Cookies 文件',
    desc: '指定 Netscape 格式的 cookies 文件路径',
    category: 'auth',
    type: 'text',
    placeholder: '~/cookies.txt',
    argName: 'FILE',
  },
  {
    id: 'username',
    flag: '--username',
    shortFlag: '-u',
    label: '用户名',
    desc: '使用账号密码认证时的用户名',
    category: 'auth',
    type: 'text',
    placeholder: 'username',
    argName: 'USERNAME',
  },
  {
    id: 'password',
    flag: '--password',
    shortFlag: '-p',
    label: '密码',
    desc: '账号密码认证时的密码',
    category: 'auth',
    type: 'text',
    placeholder: 'password',
    argName: 'PASSWORD',
  },
  {
    id: 'videoPassword',
    flag: '--video-password',
    label: '视频密码',
    desc: '受密码保护视频的访问密码',
    category: 'auth',
    type: 'text',
    placeholder: 'password',
    argName: 'PASSWORD',
  },
  {
    id: 'apMso',
    flag: '--ap-mso',
    label: 'API 提供商',
    desc: '多系统运营商（MSO）登录标识，用于 TV Everywhere',
    category: 'auth',
    type: 'text',
    placeholder: 'Comcast_SSO',
    argName: 'MSO',
  },
  {
    id: 'apUsername',
    flag: '--ap-username',
    label: 'API 用户名',
    desc: 'MSO 登录用户名',
    category: 'auth',
    type: 'text',
    placeholder: 'username',
    argName: 'USERNAME',
  },
  {
    id: 'apPassword',
    flag: '--ap-password',
    label: 'API 密码',
    desc: 'MSO 登录密码',
    category: 'auth',
    type: 'text',
    placeholder: 'password',
    argName: 'PASSWORD',
  },

  // ============ 播放列表 ============
  {
    id: 'noPlaylist',
    flag: '--no-playlist',
    label: '仅下载视频',
    desc: '若 URL 同时指向视频与播放列表，仅下载视频',
    category: 'general',
    type: 'switch',
  },
  {
    id: 'playlistItems',
    flag: '--playlist-items',
    label: '播放列表条目',
    desc: '指定要下载的条目，如 1-5,8,10-12',
    category: 'general',
    type: 'text',
    placeholder: '1-5,8',
    argName: 'ITEMS',
  },
  {
    id: 'playlistStart',
    flag: '--playlist-start',
    label: '起始条目',
    desc: '从第 N 个条目开始下载',
    category: 'general',
    type: 'number',
    placeholder: '1',
    argName: 'NUMBER',
  },
  {
    id: 'playlistEnd',
    flag: '--playlist-end',
    label: '结束条目',
    desc: '下载到第 N 个条目为止',
    category: 'general',
    type: 'number',
    placeholder: 'last',
    argName: 'NUMBER',
  },
  {
    id: 'playlistReverse',
    flag: '--playlist-reverse',
    label: '逆序下载',
    desc: '以逆序下载播放列表条目',
    category: 'general',
    type: 'switch',
  },
  {
    id: 'playlistRandom',
    flag: '--playlist-random',
    label: '随机下载',
    desc: '以随机顺序下载播放列表条目',
    category: 'general',
    type: 'switch',
  },

  // ============ 冗余与调试 ============
  {
    id: 'simulate',
    flag: '--simulate',
    shortFlag: '-s',
    label: '模拟下载',
    desc: '不实际下载，仅模拟操作',
    category: 'verbosity',
    type: 'switch',
  },
  {
    id: 'skipDownload',
    flag: '--skip-download',
    label: '跳过下载',
    desc: '不下载视频，仅执行提取/后处理',
    category: 'verbosity',
    type: 'switch',
  },
  {
    id: 'quiet',
    flag: '--quiet',
    shortFlag: '-q',
    label: '安静模式',
    desc: '减少输出信息',
    category: 'verbosity',
    type: 'switch',
  },
  {
    id: 'noWarnings',
    flag: '--no-warnings',
    label: '忽略警告',
    desc: '不输出警告信息',
    category: 'verbosity',
    type: 'switch',
  },
  {
    id: 'verbose',
    flag: '--verbose',
    shortFlag: '-v',
    label: '详细输出',
    desc: '输出详细的调试信息',
    category: 'verbosity',
    type: 'switch',
  },
  {
    id: 'print',
    flag: '--print',
    label: '打印字段',
    desc: '打印指定字段而非下载，如 "%(title)s"',
    category: 'verbosity',
    type: 'text',
    placeholder: '%(title)s',
    argName: 'TEMPLATE',
  },
  {
    id: 'dumpJson',
    flag: '--dump-json',
    label: '输出 JSON',
    desc: '输出视频信息为 JSON（不下载）',
    category: 'verbosity',
    type: 'switch',
  },
  {
    id: 'listFormats',
    flag: '--list-formats',
    shortFlag: '-F',
    label: '列出格式',
    desc: '列出所有可用的视频/音频格式',
    category: 'verbosity',
    type: 'switch',
  },
  {
    id: 'listSubs',
    flag: '--list-subs',
    label: '列出字幕',
    desc: '列出所有可用的字幕语言',
    category: 'verbosity',
    type: 'switch',
  },
  {
    id: 'noCheckCertificate',
    flag: '--no-check-certificate',
    label: '禁用证书校验',
    desc: '禁用 HTTPS 证书校验（不推荐）',
    category: 'verbosity',
    type: 'switch',
  },
  {
    id: 'encoding',
    flag: '--encoding',
    label: '文本编码',
    desc: '强制使用指定的文本编码',
    category: 'verbosity',
    type: 'text',
    placeholder: 'utf-8',
    argName: 'ENCODING',
  },

  // ============ 兼容与修复 ============
  {
    id: 'downloadArchive',
    flag: '--download-archive',
    label: '下载记录',
    desc: '记录已下载的 ID，避免重复下载',
    category: 'workarounds',
    type: 'text',
    placeholder: '~/archive.txt',
    argName: 'FILE',
  },
  {
    id: 'ageLimit',
    flag: '--age-limit',
    label: '年龄限制',
    desc: '仅下载指定年龄分级以下的内容',
    category: 'workarounds',
    type: 'number',
    placeholder: '18',
    argName: 'YEARS',
  },
  {
    id: 'matchFilter',
    flag: '--match-filter',
    label: '过滤条件',
    desc: '按条件过滤视频，如 duration < 600',
    category: 'workarounds',
    type: 'text',
    placeholder: 'duration < 600',
    argName: 'FILTER',
  },
  {
    id: 'matchTitle',
    flag: '--match-title',
    label: '标题匹配',
    desc: '仅下载标题匹配正则的视频',
    category: 'selection',
    type: 'text',
    placeholder: '教程',
    argName: 'REGEX',
  },
  {
    id: 'rejectTitle',
    flag: '--reject-title',
    label: '标题排除',
    desc: '跳过标题匹配正则的视频',
    category: 'selection',
    type: 'text',
    placeholder: '广告',
    argName: 'REGEX',
  },
  {
    id: 'date',
    flag: '--date',
    label: '指定日期',
    desc: '仅下载指定日期的视频，如 today / 20240101',
    category: 'selection',
    type: 'text',
    placeholder: 'today',
    argName: 'DATE',
  },
  {
    id: 'datebefore',
    flag: '--datebefore',
    label: '日期之前',
    desc: '仅下载早于指定日期的视频',
    category: 'selection',
    type: 'text',
    placeholder: '20240101',
    argName: 'DATE',
  },
  {
    id: 'dateafter',
    flag: '--dateafter',
    label: '日期之后',
    desc: '仅下载晚于指定日期的视频',
    category: 'selection',
    type: 'text',
    placeholder: 'now-1month',
    argName: 'DATE',
  },
  {
    id: 'minViews',
    flag: '--min-views',
    label: '最少播放量',
    desc: '仅下载播放量不低于此值的视频',
    category: 'selection',
    type: 'number',
    placeholder: '1000',
    argName: 'COUNT',
  },
  {
    id: 'maxViews',
    flag: '--max-views',
    label: '最多播放量',
    desc: '仅下载播放量不超过此值的视频',
    category: 'selection',
    type: 'number',
    placeholder: '100000',
    argName: 'COUNT',
  },
  {
    id: 'cacheDir',
    flag: '--cache-dir',
    label: '缓存目录',
    desc: '指定 yt-dlp 缓存文件的位置',
    category: 'filesystem',
    type: 'text',
    placeholder: '~/.cache/yt-dlp',
    argName: 'DIR',
  },
  {
    id: 'noCacheDir',
    flag: '--no-cache-dir',
    label: '禁用缓存',
    desc: '禁用文件系统缓存',
    category: 'filesystem',
    type: 'switch',
  },
  {
    id: 'trimFileName',
    flag: '--trim-file-name',
    label: '截断文件名',
    desc: '限制文件名最大长度（字符数）',
    category: 'filesystem',
    type: 'number',
    placeholder: '80',
    argName: 'LENGTH',
  },
]

// 按分类分组
export function getOptionsByCategory() {
  const map = new Map<string, OptionDef[]>()
  for (const opt of OPTIONS_CATALOG) {
    const arr = map.get(opt.category) ?? []
    arr.push(opt)
    map.set(opt.category, arr)
  }
  return map
}

export function findOption(id: string) {
  return OPTIONS_CATALOG.find((o) => o.id === id)
}